version: '2'

services:
  conway:
    tty: true
    build: ./docker/docker-image/
    command: node
    environment:
      - PORT=8080
      - NODE_ENV=development
    ports:
      - 8080:8080
      - 8081:8081
      - 5555:5555
    volumes:
      - ./:/home/dev
